# Generated by Django 4.2.7 on 2025-08-26 20:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lote', models.CharField(max_length=100, verbose_name='Número do Lote')),
                ('validade', models.DateField(verbose_name='Data de Validade')),
                ('quantidade_recebida', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade Recebida')),
                ('fornecedor', models.CharField(max_length=200, verbose_name='Fornecedor')),
                ('nota_fiscal_ref', models.CharField(blank=True, max_length=100, verbose_name='Referência NF')),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Preço Unitário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['validade', 'lote'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código do Paciente')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_comum', models.CharField(max_length=200, verbose_name='Nome Comum')),
                ('nome_comercial', models.CharField(blank=True, max_length=200, verbose_name='Nome Comercial')),
                ('concentracao', models.CharField(max_length=100, verbose_name='Concentração')),
                ('apresentacao', models.CharField(max_length=100, verbose_name='Apresentação')),
                ('unidade', models.CharField(default='ampola', max_length=50, verbose_name='Unidade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('estoque_minimo_default', models.DecimalField(decimal_places=2, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Estoque Mínimo Padrão')),
                ('dias_alerta_vencimento', models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dias para Alerta de Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substances_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Substância',
                'verbose_name_plural': 'Substâncias',
                'ordering': ['nome_comum'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Unidade')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('responsavel', models.CharField(blank=True, max_length=100, verbose_name='Responsável')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UnitTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código da Transferência')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('motivo', models.TextField(verbose_name='Motivo da Transferência')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_transito', 'Em Trânsito'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data do Envio')),
                ('data_recebimento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Recebimento')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.batch', verbose_name='Lote')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.substance', verbose_name='Substância')),
                ('unidade_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recebidas_transfer', to='inventory.unit', verbose_name='Unidade Destino')),
                ('unidade_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to='inventory.unit', verbose_name='Unidade Origem')),
            ],
            options={
                'verbose_name': 'Transferência entre Unidades',
                'verbose_name_plural': 'Transferências entre Unidades',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('correcao', 'Correção'), ('ajuste', 'Ajuste'), ('perda', 'Perda'), ('transferencia_saida', 'Transferência - Saída'), ('transferencia_entrada', 'Transferência - Entrada')], max_length=25, verbose_name='Tipo')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('paciente_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome do Paciente')),
                ('procedimento', models.TextField(blank=True, verbose_name='Procedimento')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.batch', verbose_name='Lote')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.patient', verbose_name='Paciente')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.substance', verbose_name='Substância')),
                ('unidade_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recebidas', to='inventory.unit', verbose_name='Unidade Destino')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unit', verbose_name='Unidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='unidade_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unit', verbose_name='Unidade Principal'),
        ),
        migrations.AddField(
            model_name='batch',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.substance', verbose_name='Substância'),
        ),
        migrations.AddField(
            model_name='batch',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unit', verbose_name='Unidade'),
        ),
        migrations.CreateModel(
            name='SubstanceUnitConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Estoque Mínimo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo nesta Unidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.substance', verbose_name='Substância')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unit', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Configuração por Unidade',
                'verbose_name_plural': 'Configurações por Unidade',
                'unique_together': {('substance', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantidade em Estoque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.batch', verbose_name='Lote')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.substance', verbose_name='Substância')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unit', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoque',
                'ordering': ['batch__validade', 'substance__nome_comum'],
                'unique_together': {('substance', 'batch', 'unit')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('lote', 'substance', 'unit')},
        ),
    ]
