# Generated by Django 4.2.7 on 2025-09-13 02:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_advanced_patient_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferNew',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número da Transferência')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_transito', 'Em Trânsito'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('data_recebimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por')),
                ('unidade_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_recebidas', to='inventory.unit', verbose_name='Unidade de Destino')),
                ('unidade_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_enviadas', to='inventory.unit', verbose_name='Unidade de Origem')),
            ],
            options={
                'verbose_name': 'Transferência Nova',
                'verbose_name_plural': 'Transferências Novas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='TransferItemNew',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('batch_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_entrada', to='inventory.batch', verbose_name='Lote de Destino')),
                ('batch_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_saida', to='inventory.batch', verbose_name='Lote de Origem')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.substance', verbose_name='Substância')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventory.transfernew', verbose_name='Transferência')),
            ],
            options={
                'verbose_name': 'Item de Transferência Nova',
                'verbose_name_plural': 'Itens de Transferência Nova',
            },
        ),
    ]
