# Generated by Django 4.2.7 on 2025-09-13 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_transfernew_transferitemnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibilityTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número do Termo')),
                ('medico_responsavel', models.CharField(max_length=200, verbose_name='Médico Responsável')),
                ('crm_medico', models.CharField(max_length=20, verbose_name='CRM do Médico')),
                ('data_aplicacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Aplicação')),
                ('dosagem', models.CharField(max_length=100, verbose_name='Dosagem')),
                ('via_administracao', models.CharField(default='Subcutânea', max_length=100, verbose_name='Via de Administração')),
                ('observacoes_medicas', models.TextField(blank=True, verbose_name='Observações Médicas')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('assinado', models.BooleanField(default=False, verbose_name='Assinado pelo Paciente')),
                ('data_assinatura', models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura')),
                ('receita_medica', models.CharField(blank=True, max_length=100, verbose_name='Número da Receita Médica')),
                ('data_receita', models.DateField(blank=True, null=True, verbose_name='Data da Receita')),
                ('aplicado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_aplicados', to=settings.AUTH_USER_MODEL, verbose_name='Aplicado por')),
                ('gerado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_gerados', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.patient', verbose_name='Paciente')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.substance', verbose_name='Substância')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.unit', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Termo de Responsabilidade',
                'verbose_name_plural': 'Termos de Responsabilidade',
                'ordering': ['-data_geracao'],
            },
        ),
    ]
