# Generated by Django 4.2.7 on 2025-09-13 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_responsibilityterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibleDoctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('crm', models.CharField(max_length=20, verbose_name='CRM')),
                ('especialidade', models.CharField(blank=True, max_length=100, verbose_name='Especialidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Médico Responsável',
                'verbose_name_plural': 'Médicos Responsáveis',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='responsibilityterm',
            name='crm_medico',
        ),
        migrations.CreateModel(
            name='TermTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Template')),
                ('tipo', models.CharField(choices=[('full_care', 'Protocolo Full Care'), ('injetavel_geral', 'Injetáveis em Geral'), ('controlada', 'Substâncias Controladas'), ('personalizado', 'Personalizado')], default='full_care', max_length=20, verbose_name='Tipo de Template')),
                ('titulo', models.CharField(default='TERMO DE CONSENTIMENTO LIVRE, ESCLARECIDO E DECLARAÇÃO DE RESPONSABILIDADE', max_length=300, verbose_name='Título do Termo')),
                ('conteudo', models.TextField(help_text='\n        Variáveis disponíveis:\n        {{PACIENTE_NOME}} - Nome do paciente\n        {{PACIENTE_RG}} - RG do paciente  \n        {{PACIENTE_CPF}} - CPF do paciente\n        {{PACIENTE_ENDERECO}} - Endereço do paciente\n        {{MEDICO_NOME}} - Nome do médico responsável\n        {{MEDICO_CRM}} - CRM do médico\n        {{PROTOCOLO_NOME}} - Nome do protocolo (ex: Full Care)\n        {{MEDICAMENTOS}} - Lista de medicamentos\n        {{LOCAL}} - Local (Ribeirão Preto/SP ou Bauru/SP)\n        {{DATA_ATUAL}} - Data atual\n        {{DATA_ENTREGA}} - Data da entrega dos medicamentos\n        ', verbose_name='Conteúdo do Termo')),
                ('versao', models.CharField(default='1.0', max_length=10, verbose_name='Versão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('observacoes_versao', models.TextField(blank=True, help_text='Descreva as mudanças jurídicas ou atualizações feitas', verbose_name='Observações da Versão')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_templates_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_templates_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Template de Termo',
                'verbose_name_plural': 'Templates de Termos',
                'ordering': ['-data_modificacao'],
            },
        ),
        migrations.AddField(
            model_name='responsibilityterm',
            name='template_usado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.termtemplate', verbose_name='Template Utilizado'),
        ),
        migrations.AlterField(
            model_name='responsibilityterm',
            name='medico_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.responsibledoctor', verbose_name='Médico Responsável'),
        ),
    ]
